# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='number',
            field=models.IntegerField(),
        ),
    ]
