# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20171113_0013'),
        ('professor', '0004_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.ProfessorName')),
            ],
        ),
    ]
