# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
